FROM adoptopenjdk/openjdk11:alpine-jre

# Create an application directory
RUN mkdir -p /app

# The /app directory should act as the main application directory
WORKDIR /app

# Copy or project directory (locally) in the current directory of our docker image (/app)
COPY pom.xml /app
COPY src /app/src

RUN mvn spring-boot:build-image